# Reflector configuration file for the systemd service.
# See "reflector --help" for details.
# Replicates tested command: reflector --verbose --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist

--save /etc/pacman.d/mirrorlist
--protocol https
--latest 20
--sort rate
--verbose
