# Base config - foot 1.27
# man foot.ini

[main]
font=JetBrainsMono Nerd Font Mono:size=12
font-bold=JetBrainsMono Nerd Font Mono:bold:size=12
font-italic=JetBrainsMono Nerd Font Mono:italic:size=12
font-bold-italic=JetBrainsMono Nerd Font Mono:bold:italic:size=12
pad=6x2
selection-target=clipboard

[colors-dark]
alpha=0.95
background=282828
foreground=ebdbb2
# Normal colors
regular0=282828
regular1=cc241d
regular2=98971a
regular3=d79921
regular4=458588
regular5=b16286
regular6=689d6a
regular7=a89984
# Bright colors
bright0=928374
bright1=fb4934
bright2=b8bb26
bright3=fabd2f
bright4=83a598
bright5=d3869b
bright6=8ec07c
bright7=fbf1c7
# Selection and search
selection-foreground=fbf1c7
selection-background=504945
search-box-no-match=fbf1c7 cc241d
search-box-match=fbf1c7 504945
jump-labels=282828 fabd2f
urls=458588

[scrollback]
lines=10000

[mouse]
hide-when-typing=yes

[csd]
preferred=server
