# Base config - foot 1.27
# man foot.ini

[main]
font=CaskaydiaCove Nerd Font Mono:size=12
font-bold=CaskaydiaCove Nerd Font Mono:bold:size=12
font-italic=CaskaydiaCove Nerd Font Mono:italic:size=12
font-bold-italic=CaskaydiaCove Nerd Font Mono:bold:italic:size=12
pad=8x8 center
selection-target=clipboard

[colors-dark]
alpha=0.95

[scrollback]
lines=10000

[mouse]
hide-when-typing=yes

[csd]
preferred=server
